console.log("my first console project");
var first_name="Antra";
var last_name="Jain";
var full_name=first_name.concat(last_name);
console.log(full_name);
var a=10;
var b=5;
var add=a+b;
console.log(add);
var c=6;
var d=2;
var subtract=c-d;
console.log(subtract);
